### ISSUE TITLE
cannot play videos when loaded via AJAX

### ISSUE THREAD

**Issue by ErikBorra** [distantnative/oembed#69]
Thanks for a great plugin! 

When i do the following 
```
<?php echo $data->video()->oembed(); ?>
```
video playback works on click, unless when retrieved via AJAX. In the latter case, clicking does not start the video. Any idea?

**Comment by distantnative** [comment]
I would assume that is because the actual video HTML part is still missing when the site is loaded and the javascript listener is attached - so it doesn't find any video to bind the playback event to it.

You should make sure to runt he following javascript again after the video has been loaded via AJAX:
```js
var thumb = document.getElementsByClassName('kirby-plugin-oembed__thumb');

  for (var i = 0; i < thumb.length; i++) {
      thumb[i].addEventListener('click', pluginOembedLoadLazyVideo, false);
  }
```

**Comment by ErikBorra** [comment]
Awesome, that worked. Thanks so much!
